CyC.GestorDeContactosWeb/WebAplicacion/Controllers/ContactoController.cs
using CyC.GestorDeContactos.AccesoDatos.DAL;
using CyC.GestorDeContactos.AccesoDatos.DTO;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace WebAplicacion.Controllers
{
    public class ContactoController : Controller
    {
        // GET: Contacto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            List<Contacto> listaContactos = ContactoDAL.getAllContactos();
            return Json(new { data = listaContactos }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddOrEdit(string idContacto)
        {
            if (String.IsNullOrEmpty(idContacto))
            {
                return View(new Contacto());
            }
            else
            {
                return View(ContactoDAL.getContactoByGuid(Guid.Parse(idContacto)));
            }

        }

        [HttpPost]
        public ActionResult AddOrEdit(Contacto nuevoContacto)
        {
            if (nuevoContacto.UIDContacto == null)
            {
                nuevoContacto.UIDContacto = Guid.NewGuid();
                nuevoContacto.UIDDireccion = Guid.Parse("849B3C32-BFEA-4FC2-AA2A-068AD170F429");
                ContactoDAL.createContacto(nuevoContacto);
            }
            else
            {
                ContactoDAL.updateContacto(nuevoContacto);
            }

            return GetData();
        }
    }
}

CyC.GestorDeContactosWeb/WebAplicacion/Views/Contacto/AddOrEdit.cshtml
@model CyC.GestorDeContactos.AccesoDatos.DTO.Contacto
@{
    ViewBag.Title = "AddOrEdit";
}

<br/>
<div id="contactoForm" class="container" role="dialog" style="background-color: #FFFFFF;">
    @using (Html.BeginForm("AddOrEdit", "Contacto", FormMethod.Post, new { onsubmit = "return SubmitForm(this)"}))
    {
        @Html.HiddenFor(model => model.UIDContacto)
        <div class="form-froup">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label" })
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-froup">
            @Html.LabelFor(model => model.Email, new { @class = "control-label" })
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-froup">
            @Html.LabelFor(model => model.Telefono, new { @class = "control-label" })
            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-froup">
            @Html.LabelFor(model => model.Movil, new { @class = "control-label" })
            @Html.EditorFor(model => model.Movil, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <br/>
        <div class="form-froup">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            <input type="reset" value="Cancelar" class="btn btn-warning" />
        </div>
    }

</div>

CyC.GestorDeContactosWeb/WebAplicacion/Views/Contacto/Index.cshtml
@{
    ViewBag.Title = "Contactos";
}


<h2 style="margin-top:10px">Listado de contactos</h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Contacto")')"><i class="fas fa-plus"></i> Nuevo contacto</a>
<table id="contactosTable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Telefono</th>
            <th>Movil</th>
            <th></th>
        </tr>
    </thead>
</table>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css">

@section scripts{

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        var popup,datatable;
        $(document).ready(function () {
            datatable = $('#contactosTable').DataTable({
                "ajax": {
                    "url": "GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "Nombre" },
                    { "data": "Email" },
                    { "data": "Telefono" },
                    { "data": "Movil" },
                    {
                        "data": "UIDContacto", "render": function (data) {
                            return "<a class='btn btn-warning btn-sm' style='margin-left:5px' onclick=PopupForm('@Url.Action("AddOrEdit","Contacto")/&#34" + data + "&#34')><i class='fa fa-pencil'></i> Editar</a><a class='btn btn-danger btn-sm' style='margin-left:5px'><i class='fa fa-trash'></i> Borrar</a>"
                        },
                        "orderable": false,
                        "searchable": false
                    }
                ],
                //"language": {
                //    "lengthMenu": "Mostrando _MENU_ registros por página",
                //    "zeroRecords": "No se encontraron registros",
                //    "info": "Mostrando página _PAGE_ de _PAGES_",
                //    "infoEmpty": "No hay registros disponibles",
                //    "infoFiltered": "(Filtrado por _MAX_ total de registros)"
                //}
            });
        });

        function PopupForm(url) {
            $.get(url)
            .done(function (response) {
                var formDiv = $('<div/>');
                formDiv.html(response);
                popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    titel: 'Rellene campos de contacto',
                    height: 300,
                    width: 280,
                    close: function () {
                        popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $ajax({
                type: "POST",
                url: form.action,
                data: $(form).serialize(),
                success: function (data) {
                    if (data.success) {
                        popup.dialog('close');
                        datatable.ajax.reload();
                    }
                }
            })
        }
    </script>


        }